

[app_config]

# بيانات المستخدمين
[app_config.users.admin]
password = "PASSWORD"
credential_path = "google_credentials/account_1"
post_count = 0

[[app_config.users.admin.blogs]]
name = "المدونة الرئيسية"
id = "3714169846779613939"

# -------- مستخدم ثاني --------
[app_config.users.user_ali]
password = "strong123"
credential_path = "google_credentials/account_1"
post_count = 15

[app_config.users.user_ali.blogger_settings]
blog_id = "3714169846779613939"
api_key = "AIzaSyApcboiDeM28sEqhKK517jgl2_dshOPtYA"

[app_config.users.user_ali.telegram_settings]
bot_token = "7642666619:AAH3-MtRPnv4P9jFUnZW5zajArMwuWC-r-g"
channel_id = "-1002899423747"

[[app_config.users.user_ali.blogs]]
name = "دليلك في سوريا"
id = "3714169846779613939"


[app_config.users.user_ali.cleaning_rules]
remove_symbols = ["{", "}", "'", "“", "”",')', '(', '[', ']', '™', '©', "»", '—', '«']
[[app_config.users.user_ali.cleaning_rules.replacements]]
find = ""
replace_with = ""


# ✅ publishing_rules معرف كجدول فرعي
[app_config.users.user_ali.publishing_rules]
[[app_config.users.user_ali.publishing_rules.replacements]]
find = "سانا"
replace_with = "حسب ما رصد دليلك نيوز الإخباري"

[[app_config.users.user_ali.publishing_rules.replacements]]
find = "سوريا"
replace_with = "الجمهورية العربية السورية"

[[app_config.users.user_ali.publishing_rules.replacements]]
find = "اسرائيل"
replace_with = "المحتلين"


[[app_config.users.user_ali.publishing_rules.replacements]]
find = "أثر برس"
replace_with = ""



[google_creds]
account_1_token = """
a0AQQ_BDQOQ0mkz50kzujYUbkrFGeJI79UY1OkEdg1qsSOA7NCV3o3csNMdzeeDkSTnSR3DaSWJsMbYa2ZXiWaWZmr3vzakfXRkJGRCb9PWHRIayf5cQrabnlllYs00u5MN
"""